      # base16-equilibrium-dark
      # base16-equilibrium-grey-dark
      # base16-eris
      # base16-expresso
      # base16-evenok-dark
      # base16-flexoki-dark
      # base16-framer
      # base16-gigavolt
      # base16-github-dark
      # base16-google-dark
      # base16-gotham
      # base16-gruber
      # base16-gruvbox-dark-hard
      # base16-gruvbox-dark-pale
              # gruvbox-material-dark-hard
              # hardcore
              # hardhacker
              # harmonic-dark
              # harmonic16-dark
              # heetch
              # helios
              # horizon-dark
              # horizon-terminal-dark
              # humanoid-dark
              # ia-dark
              # icy
              # irblack
              # isotope
              # kanagawa-dragon
              # linux-vt
              # macontosh
              # material-darker
              # material-vivid
              # measured-dark
              # mellow-purple
              # monokai
              # mountain
              # ocean
              # oceanicnext
              # onedark
          # # # onedark-dark 
              # outrun-dark
              # pablo
              # papercolor-dark
              # penumbra-dark-contrast-plus-plus
              # phd
              # pinky
              # pop
              # precious-dark-eleven
              # primer-dark
              # purpledream
              # railscasts
              # rose-pine
              # rose-pine-moon
              # schemer-dark
              # selenized-black
              # seti
              # shadesmear-dark
              # snazzy
              # soft-server
              # solarflare
              # solarized-dark
              # gruvbox
              # 0x96f
              # 3024
              # atelier-dune
              # atelier-estuary
              # atelier-forest
              # atelier-lakeside
              # atelier-savanna
              # atelier-seaside
              # ayu-dark
              # ayu-mirage
              # blueish
              # ashes
              # brewer
              # bright
              # brogrammer
              # catppuccin
              # catppuccin-macchiato
              # catppuccin-mocha
              # chalk
              # chinoisertie-midnight
              # circus
              # classic-dark
              # colors
              # da-one-black
              # darkmoss
              # darkviolet
              # decaf
              # deep-oceanic-next
              # default-dark
              # digital-rain
              # dracula
              # eighties
              # equilibrium-dark
              # equilibrium-gray-dark
